In [5]:
import requests
from IPython.core.display import HTML
# HTML(f"""
# <style>
# @import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
# </style>
# """)

# Linear Algebra
<article class="message is-info">
  <div class="message-header">Overview</div>
  <div class="message-body">
  
  This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.

  
  </div>
</article>


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5],
    [3/2, 0.5],
    [0.25, 1]
])

## Matrix Operations
<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [15]:
# Write your solution here
print(A-B)

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-file-ppt" style="color: blue;"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).

2. Explain why the results are different.

3. Calculate $DE$ and $ED$ in the code cell below.

4. Explain what happens and why.




</div></article>



In [78]:
# Write your solution here
print("1. ")
print(" AC: \n", A @ C)
print(" CA: \n", C @ A)

print("2. Explain why they are different: \n",
      " Matrix multiplication of two matrices can be conceptualized " \
      "as a series of consecutive inner products between corresponding row-column pairs.",
      "AC will iterate through the rows of A and columns of C e.g. " \
      "The first element in AC is calculated as the inner product of the first row of A and the first column of C",
      "In contrast, CA will iterate through the rows of C and columns of A")

print("3. ")
print(" DE: \n", D @ E)
#print("ED: \n", E @ D)
try: np.dot(E,D)
except Exception as e: print(" Exception: ", e)
try: E @ D
except Exception as e: print(" Exception: ", e)

print("4. Explain what happens and why.\n",
      "To be able to find the inner product of two matrices, " \
      "the number of columns in the first matrix and rows in the second matrix has to be equal.", 
      "This holds for DE (as D has 3 columns and E has 3 rows), " \
      "but not for ED (since E has 2 columns and E has 3 rows), therefore an exception is thrown.")



1. 
 AC: 
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
 CA: 
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
2. Explain why they are different: 
  Matrix multiplication of two matrices can be conceptualized as a series of consecutive inner products between corresponding row-column pairs. AC will iterate through the rows of A and columns of C e.g. The first element in AC is calculated as the inner product of the first row of A and the first column of C In contrast, CA will iterate through the rows of C and columns of A
3. 
 DE: 
 [[8.625  3.5   ]
 [2.3125 1.625 ]
 [1.5    2.125 ]]
 Exception:  shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)
 Exception:  matmul: Input operand 1 has a mismatch in

<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication - Hadamard product</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators and identify which one is matrix multiplication.



</div></article>



In [85]:
# Write your solution here
print("1. ")
print("A*B: \n", A*B)
print("2. Explain the difference between the `*` and `@` operators and " \
"identify which one is matrix multiplication.\n", 
" Matrix multiplication is the one using the `@` operator. \n" 
" As explained in the previous task, this can be conceptualized " \
"as a series of consecutive inner products between corresponding row-column pairs" \
"e.g. each element in the resulting matrix is calculated as the inner product between corresponding row-column pairs. \n"
" The elementwise multiplication using the `*` operator just returns a matrix of the products of the elements of the same index in each matrix")


1. 
A*B: 
 [[-16.           7.5         -4.66666667   3.25      ]
 [ -6.           3.66666667  -2.5          1.8       ]
 [ -2.66666667   1.75        -1.2          0.83333333]
 [ -1.           0.6         -0.33333333   0.14285714]]
2. Explain the difference between the `*` and `@` operators and identify which one is matrix multiplication.
  Matrix multiplication is the one using the `@` operator. 
 As explained in the previous task, this can be conceptualized as a series of consecutive inner products between corresponding row-column pairse.g. each element in the resulting matrix is calculated as the inner product between corresponding row-column pairs. 
 The elementwise multiplication using the `*` operator just returns a matrix of the products of the elements of the same index in each matrix


---
