In [2]:
import requests
from IPython.core.display import HTML
#HTML(f"""
#<style>
#@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
#</style>
#""")

### Q2 Exercise Week 4 (Linear Transformations)

#### (a) Use the tutorial to focus on exploring linear transformations in 2D and 3D spaces, including operations such as scaling, shearing, reflections, rotations, and translations, while drawing connections to their extensions in higher-dimensional linear transformations. Additionally, you should explain the relationship between linear transformations and non-linear transformations including affine, thus bridging the gap between linear and more complex transformations.
_[tutorial-link](../Tutorials/04-transformations.ipynb)_
- Linear transformations
- transformations in 2D and 3D spaces
- types of linear transformations
    - scaling, shearing, reflections, and rotations (and extensions to higher dimensional linear transformations) 
    - non-commutativity
- linear transformations vs non-linear transformations including affine
    - translations
    - homogeneous coordinates for affine transformations

#### (b) Focus on how linear and non-linear models can be learned using matrix inverses. Discuss the relationship between model complexity (e.g., polynomial degree) and the amount of data needed to accurately train these models with matrix inverses.
- learning models using matrix inverses
    - seperate inputs/labels
    - construct design matrix
    - compute weights using inverse (accounting for non-square matrices)
- Examples:
    - linear model (inClass3)
    - polynomial model (increased complexity) (02)

#### (c) Focus on affine transformations, homogeneous coordinates and composition of linear transformations.
- composition of linear transformations (mixing multiple transformations into one matrix)
    - associativity
    - non-commutativity
- affine transformations (last part of [tutorial](../Tutorials/04-transformations.ipynb))
    - affine transformations
    - homogeneous coordinates for translations

# Linear Algebra
<article class="message is-info">
  <div class="message-header">Overview</div>
  <div class="message-body">
  
  This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.

  
  </div>
</article>


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 1: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [4]:
# 1
print("TASK 1.1")
Ainv = np.linalg.inv(A)
print("A^-1: \n", Ainv)
Cinv = np.linalg.inv(C)
print("C^-1: \n", Cinv)

print("\nTASK 1.2")
AAinv = A@Ainv
print("AA^-1: \n", AAinv)
CCinv = C@Cinv
print("CC^-1: \n", CCinv)
#The limitations of floating points gives a bit of rounding error, 
# but it is essentially the identity matrix. 
#If we round it we get:
print("AA^-1 rounded: \n", AAinv.round())
print("CC^-1 rounded: \n", CCinv.round())


TASK 1.1
A^-1: 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
C^-1: 
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]

TASK 1.2
AA^-1: 
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.55431223e-15  1.00000000e+00 -2.38919995e-14 -5.98632255e-14]
 [ 1.11022302e-16 -3.44909286e-14  1.00000000e+00 -8.27486228e-14]
 [-3.45755171e-15  1.10387889e-14 -4.78981933e-14  1.00000000e+00]]
CC^-1: 
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.09734485e-14  1.00000000e+00  3.35864669e-13 -1.96731520e-14]
 [-4.02147451e-15 -8.61903141e-14  1.00000000e+00 -1.43342128e-14]
 [-4.02147451e-15  2.74965236e-14 -1.86591483e-13  1.00000000e+00]]
AA^-1 rounded: 
 [[ 1.  0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1. -0.]
 [-0.  0. -0.  1.]]
CC^-1 rounded: 
 [[ 1.  0.  0.  0.]
 [-0.  1.  0.

## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 2: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [5]:
print("TASK 2")
DinvEinv = np.linalg.inv(D)@np.linalg.inv(E)
print("D^-1 E^-1: \n", DinvEinv)
EDinv = np.linalg.inv(E@D)
print("(ED)^-1: \n", EDinv)

DEinv = np.linalg.inv(D@E)
print("(DE)^-1: \n", DEinv)

TASK 2
D^-1 E^-1: 
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
(ED)^-1: 
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
(DE)^-1: 
 [[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 3: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [6]:
print("TASK 3.1")
detA = np.linalg.det(A)
print("det(A): \n", detA)
detB = np.linalg.det(B)
print("det(B): \n", detB)
detC = np.linalg.det(C)
print("det(C): \n", detC)

print("\nTASK 3.2")
print("Only A and C have an inverse. B is zero (basically) and do not have an inverse")

print("\nTASK 3.3")
Ainv = np.linalg.inv(A)
print("A^-1: \n", Ainv)
Binv = np.linalg.inv(B)
print("B^-1: \n", Binv)
Cinv = np.linalg.inv(C)
print("C^-1: \n", Cinv)

print("\nExplain what happens? ")
print("We see that A and C have reasonable inverses, while B's inverse contains extremely large values (on the order of 10^16).")
print("For A and C we get the identity matrix when we multiply the matrix with its inverse:")
print("A @ A^-1: \n", (A @ Ainv).round())
print("C @ C^-1: \n", (C @ Cinv).round())

print("For B, we do not:")
print("B @ B^-1: \n", (B @ Binv).round())
print("This is a sign that B is not truly invertible.")

print("When we try to invert matrix B (which has det ≈ 0), NumPy gives us a result. But the huge numbers like 3.00e+16 is a warning sign that the matrix is not truly invertible.")
print("But why does this happen? Since the determinant is only very close to zero, but not actually zero, NumPy can compute an inverse. However, because the determinant is so small, numphy has to use a very large number for the inverse, and since floating point numbers have limited precision, this leads to inaccuracies in the result.")


TASK 3.1
det(A): 
 1.6534391534392702e-07
det(B): 
 2.7733391199176e-32
det(C): 
 1.0498026371041163e-07

TASK 3.2
Only A and C have an inverse. B is zero (basically) and do not have an inverse

TASK 3.3
A^-1: 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
B^-1: 
 [[-3.00239975e+16  4.80383960e+16 -6.00479950e+15 -1.20095990e+16]
 [-4.80383960e+16  7.20575940e+16 -0.00000000e+00 -2.40191980e+16]
 [-6.00479950e+15  0.00000000e+00  1.80143985e+16 -1.20095990e+16]
 [ 1.20095990e+16 -2.40191980e+16  1.20095990e+16 -0.00000000e+00]]
C^-1: 
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]

Explain what happens? 
We see that A and C have reasonable inverses, while B's inverse contains extremely large values (on the order of 10^16).
For A and C we get the identity matrix when we multiply the matrix with its inverse:
A @ A^-

<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 4: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [7]:
print("TASK 4")
Dinv = np.linalg.inv(D)
DinvT = Dinv.T
print("D^-1^T: \n", DinvT)

DT = D.T
DTinv = np.linalg.inv(DT)
print("D^T^-1: \n", DTinv)

TASK 4
D^-1^T: 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
D^T^-1: 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 5: Solving linear equation systems (MANDATORY!)</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [8]:
print("a)")
aA = np.array([[2,3],[1,1]])
print("det(aA): ", np.linalg.det(aA))
print("aA is invertible, since its determinant is not 0.")
ab = np.array([-1,0])
ax = np.linalg.inv(aA)@ab
print(ax)

print("b)")
bA = np.array([[1,0],[0,1]])
print("det(bA): ", np.linalg.det(bA))
print("bA is invertible, since its determinant is not 0.")
bb = np.array([5,7])
bx = np.linalg.inv(bA)@bb
print(bx)

print("c)")
cA = np.array([[0,1],[-2,-3]])
print("det(cA): ", np.linalg.det(cA))
print("cA is invertible, since its determinant is not 0.")
cb = np.array([-1,2])
cx = np.linalg.inv(cA)@cb
print(cx)

print("d)")
dA = np.array([[1,-3,3],[1,-5,3],[4,-6,6]])
print("det(dA): ", np.linalg.det(dA))
print("dA is invertible, since its determinant is not 0.")
db = np.array([0.5,0.5,1])
dx = np.linalg.inv(dA)@db
print(dx)

print("e)")
eA = np.array([[2,3,4],[1,1,4],[2,5,4]])
print("det(eA): ", np.linalg.det(eA))
print("eA is invertible, since its determinant is not 0.")
eb = np.array([2,-2,3])
ex = np.linalg.inv(eA)@eb
print(ex)

print("f)")
fA = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("det(fA): ", np.linalg.det(fA))
print("fA is not invertible, since its determinant is 0.")
print("This means that the system either has no solutions or infinitely many solutions (NOT a unique solution).")
fb = np.array([2,-2,3])
fx = np.linalg.inv(fA)@fb
print(fx)


a)
det(aA):  -1.0
aA is invertible, since its determinant is not 0.
[ 1. -1.]
b)
det(bA):  1.0
bA is invertible, since its determinant is not 0.
[5. 7.]
c)
det(cA):  2.0
cA is invertible, since its determinant is not 0.
[ 0.5 -1. ]
d)
det(dA):  12.000000000000005
dA is invertible, since its determinant is not 0.
[-5.55111512e-17  1.58603289e-17  1.66666667e-01]
e)
det(eA):  -7.999999999999998
eA is invertible, since its determinant is not 0.
[ 3.     0.5   -1.375]
f)
det(fA):  -1.8488927466117412e-32
fA is not invertible, since its determinant is 0.
This means that the system either has no solutions or infinitely many solutions (NOT a unique solution).
[-1.80143985e+16 -3.60287970e+16  5.40431955e+16]


## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 6: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          <i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [9]:
def matmul(a, b):
    AB = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            sum = 0
            for k in range(len(b)):
                sum += a[i][k] * b[k][j]
            AB[i][j] = sum
    return AB

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

print("My function: \n", matmul(ma, mb))
print("Numpy function: \n", np.array(ma) @ np.array(mb))

My function: 
 [[ 33.   6.  26.]
 [ 78.  21.  77.]
 [123.  36. 128.]]
Numpy function: 
 [[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]


<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 7: Extra exercises</span>
        <span class="has-text-right">
          <i class="bi bi-lightbulb-fill"></i>
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

